name: Build Executable

on:
  release:
    types: [created]

jobs:
  build:
    runs-on: windows-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      
      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: 3.9
      
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install pyinstaller pyqt5
      
      - name: Build executable
        run: |
          pyinstaller --onefile --windowed --name "科学单位转换工具" converter.py
      
      - name: Upload executable
        uses: actions/upload-artifact@v2
        with:
          name: unit-converter
          path: dist/科学单位转换工具.exe
